# Welcome to Jekyll!
# ... (comentarios omitidos por brevedad)

# Site settings
# These are used to personalize your new site.

title: Stairway SpA | Visual Identity and Web Development That Drives Your Business
email: stairway.cl@gmail.com
description: >-
  Professional logo design, complete visual identity, and fast, secure static website development (Jekyll). We scale your brand from logo to code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stairwaycl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: stairwaycl

# Añade una variable para indicar dónde buscar la imagen principal
# Esto es solo una referencia. El plugin SEO la buscará.
social_image: https://res.cloudinary.com/ddky4mrmg/image/upload/w_1200,h_940,c_crop,g_north_west/v1762818484/stairway/ecwhtlyccako0greenqe.png

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  authors:
    output: true

defaults:
  # 1. VALORES PREDETERMINADOS PARA POSTS/AUTHORS
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # 2. VALORES PREDETERMINADOS GENERALES
  - scope:
      path: ""
    values:
      layout: "default"
  # 3. REGLAS DE PERMALINK PARA PÁGINAS
  - scope:
      path: "pages"  # Target: todo en el directorio pages/
    values:
      permalink: /:basename/

paginate: 6
paginate_path: "/blog/page:num/"
# Exclude from processing.
# ... (Excluidos omitidos por brevedad)
